apiVersion: apps/v1
kind: Deployment
metadata:
  name: votre-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: votre-app
  template:
    metadata:
      labels:
        app: votre-app
    spec:
      containers:
      - name: votre-app
        image: docker.io/Hakim06/app:latest  # Remplacez par votre image Docker
        ports:
        - containerPort: 8000  # Le port sur lequel votre application écoute